### ISSUE TITLE
Regression: into_wasm_abi requiring unnecessary trait bound

### ISSUE THREAD

**Issue by nappa85** [siefkenj/tsify#25]
This works with `tsify`, upgrading to `tsify-next` it starts giving an error about `Id` and `Value` not having a bound on `serde::Serialize`

```rust
#[derive(serde::Serialize, tsify_next::Tsify)]
#[tsify(into_wasm_abi)]
pub struct Identified<Id, Value> {
    pub id: Id,
    pub value: Value,
}
```

**Comment by Pantamis** [comment]
I suspect my PR #22 may have done it 😅

I will take a look at this.

**Comment by Pantamis** [comment]
It should be fixed by #26 can you test it ?

I have an annoying warning about an unused field when compiling, do you have it too ?

**Comment by nappa85** [comment]
Now it works, the only negative detail is the warning
```
Function `__wbg_instanceof_JsType_d5b10ea09f1d9e1c` should have snake_case name, e.g. `__wbg_instanceof_js_type_d5b10ea09f1d9e1c`rust-analyzer[non_snake_case](https://doc.rust-lang.org/rustc/?search%3Dnon_snake_case)
```

But it isn't related to this issue

**Comment by Pantamis** [comment]
Nice ! Thanks for testing the fix 👍 

Yeah I may usually get such warning in rust analyser too, I think it comes from `wasm_bindgen`

**Comment by nappa85** [comment]
Not sure about that, I remember someone pointed it out on `tsify` (and maybe proposed a fix), I'll search it out as soon I have time

**Comment by siefkenj** [comment]
Should be fixed in `v0.5.2`

**Comment by nappa85** [comment]
Sorry to reopen, but I've just found another problem:
```rust
#[derive(serde::Serialize, tsify_next::Tsify)]
#[tsify(into_wasm_abi)]
pub struct Identified<Id, Value>
where
    Id: Send,
{
    pub id: Id,
    pub value: Value,
}
```

Any trait bound, in this example `Send`, causes the macro to generate an error about the bound not being satisfied

**Comment by Pantamis** [comment]
@nappa85 I made another fix and improve our test to cover such cases. If you have other edge case where it does not work, let us know !

**Comment by nappa85** [comment]
I really hope the edge cases are terminated
